# Header
menu:
  Home: /
  About: /about
  Publications: /publications
  Projects: /projects
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- archive
- tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-1913538-2
gauges_analytics:
favicon: /favicon.png
twitter: williamjohnbert
google_plus:
fb_admins:
fb_app_id:
