# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- tag
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-1913538-2
favicon: /favicon.png
twitter: williamjohnbert
google_plus:
fb_admins:
fb_app_id: